USE ToolsStore
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--
--SK_MODEL--
--
PRINT '<<< DROP INDEX Ref221 >>>'
GO
DROP INDEX Ref221 ON dbo.RS_PRODUCT
GO

PRINT '<<< DROP INDEX FK_RS_PRODUCT_CT_MODEL >>>'
GO
DROP INDEX FK_RS_PRODUCT_CT_MODEL ON dbo.RS_PRODUCT
GO

PRINT '<<< DROP CONSTRAINT FK_RS_PRODUCT_CT_MODEL >>>'
GO
ALTER TABLE dbo.RS_PRODUCT DROP CONSTRAINT FK_RS_PRODUCT_CT_MODEL
GO

PRINT '<<< DROP TABLE CT_MODEL >>>'
GO
DROP TABLE dbo.CT_MODEL
GO

PRINT '<<< CREATE TABLE SK_MODEL >>>'
GO
CREATE TABLE dbo.SK_MODEL(
	ModelId bigint IDENTITY(1,1) NOT NULL,
	BrandId bigint NOT NULL,
	Code    bigint NOT NULL,
	Name nvarchar(500) NOT NULL,
 CONSTRAINT PK_SK_MODEL PRIMARY KEY CLUSTERED (ModelId)
)
GO

PRINT '<<< ADD INDEX AK_SK_MODEL >>>'
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_SK_MODEL ON dbo.SK_MODEL (Code)
GO

PRINT '<<< ADD CONSTRAINT FK_SK_MODEL_CT_BRAND >>>'
GO
ALTER TABLE dbo.SK_MODEL  WITH CHECK ADD CONSTRAINT FK_SK_MODEL_CT_BRAND FOREIGN KEY(BrandId)
REFERENCES dbo.CT_BRAND (BrandId)
GO

ALTER TABLE dbo.SK_MODEL CHECK CONSTRAINT FK_SK_MODEL_CT_BRAND
GO

PRINT '<<< ADD INDEX FK_SK_MODEL_CT_BRAND >>>'
GO
CREATE INDEX FK_SK_MODEL_CT_BRAND ON dbo.SK_MODEL(BrandId)
GO

PRINT '<<< ADD CONSTRAINT FK_RS_PRODUCT_SK_MODEL >>>'
GO
ALTER TABLE dbo.RS_PRODUCT  WITH CHECK ADD CONSTRAINT FK_RS_PRODUCT_SK_MODEL FOREIGN KEY(ModelId)
REFERENCES dbo.SK_MODEL (ModelId)
GO

ALTER TABLE dbo.RS_PRODUCT CHECK CONSTRAINT FK_RS_PRODUCT_SK_MODEL
GO

PRINT '<<< ADD INDEX FK_RS_PRODUCT_SK_MODEL >>>'
GO
CREATE INDEX FK_RS_PRODUCT_SK_MODEL ON dbo.RS_PRODUCT(ModelId)
GO


--
--RS_PRODUCT_CT_IMAGE--
--
PRINT '<<< DROP CONSTRAINT RefCT_IMAGE21 >>>'
GO
ALTER TABLE dbo.RS_PRODUCT DROP CONSTRAINT RefCT_IMAGE21
GO

PRINT '<<< ADD CONSTRAINT FK_RS_PRODUCT_CT_IMAGE >>>'
GO
ALTER TABLE dbo.RS_PRODUCT  WITH CHECK ADD CONSTRAINT FK_RS_PRODUCT_CT_IMAGE FOREIGN KEY(ImageId)
REFERENCES dbo.CT_IMAGE (ImageId)
GO

ALTER TABLE dbo.RS_PRODUCT CHECK CONSTRAINT FK_RS_PRODUCT_CT_IMAGE
GO

PRINT '<<< ADD INDEX FK_RS_PRODUCT_CT_IMAGE >>>'
GO
CREATE INDEX FK_RS_PRODUCT_CT_IMAGE ON dbo.RS_PRODUCT(ImageId)
GO

--
--RS_PRODUCT.EQUIPMENTID--
--
PRINT '<<< RS_PRODUCT.EQUIPMENTID >>>'
GO
ALTER TABLE dbo.RS_PRODUCT
	ADD EquipmentId BIGINT NULL;


PRINT '<<< FK_RS_PRODUCT_SK_EQUIPMENT >>>'
GO
ALTER TABLE dbo.RS_PRODUCT  WITH CHECK ADD CONSTRAINT FK_RS_PRODUCT_SK_EQUIPMENT FOREIGN KEY(EquipmentId)
REFERENCES dbo.SK_EQUIPMENT (EquipmentId)
GO

ALTER TABLE dbo.RS_PRODUCT CHECK CONSTRAINT FK_RS_PRODUCT_SK_EQUIPMENT
GO

PRINT '<<< ADD INDEX FK_RS_PRODUCT_SK_EQUIPMENT >>>'
GO
CREATE INDEX FK_RS_PRODUCT_SK_EQUIPMENT ON dbo.RS_PRODUCT(EquipmentId)
GO

PRINT '<<< ALTER TABLE RS_PRODUCT CATEGORYID, BRANDID, MODELID>>>'
GO
ALTER TABLE dbo.RS_PRODUCT
	ALTER COLUMN CategoryId BIGINT NULL;

ALTER TABLE dbo.RS_PRODUCT
	ALTER COLUMN BrandId BIGINT NULL;

ALTER TABLE dbo.RS_PRODUCT
	ALTER COLUMN ModelId BIGINT NULL;