USE ToolsStore
GO

--
--DROP INDEX--
--
PRINT '<<< DROP INDEX  FK_RS_COMING_CONTENT_RS_PRODUCT >>>'
GO
DROP INDEX FK_RS_COMING_CONTENT_RS_PRODUCT ON dbo.RS_COMING_CONTENT
GO

PRINT '<<< DROP INDEX FK_RS_ORDER_CONTENT_RS_PRODUCT >>>'
GO
DROP INDEX FK_RS_ORDER_CONTENT_RS_PRODUCT ON dbo.RS_ORDER_CONTENT
GO

PRINT '<<< DROP INDEX FK_RS_OUTGO_CONTENT_RS_PRODUCT >>>'
GO
DROP INDEX FK_RS_OUTGO_CONTENT_RS_PRODUCT ON dbo.RS_OUTGO_CONTENT
GO

PRINT '<<< DROP INDEX FK_RS_PRICE_RS_PRODUCT >>>'
GO
DROP INDEX FK_RS_PRICE_RS_PRODUCT ON dbo.RS_PRICE
GO

PRINT '<<< DROP INDEX FK_RS_RETURN_CONTENT_RS_PRODUCT >>>'
GO
DROP INDEX FK_RS_RETURN_CONTENT_RS_PRODUCT ON dbo.RS_RETURN_CONTENT
GO

PRINT '<<< DROP INDEX FK_RS_PRODUCT_CT_BRAND >>>'
GO
DROP INDEX FK_RS_PRODUCT_CT_BRAND ON dbo.RS_PRODUCT
GO

PRINT '<<< DROP INDEX FK_RS_PRODUCT_CT_CATEGORY >>>'
GO
DROP INDEX FK_RS_PRODUCT_CT_CATEGORY ON dbo.RS_PRODUCT
GO

PRINT '<<< DROP INDEX FK_RS_PRODUCT_CT_IMAGE >>>'
GO
DROP INDEX FK_RS_PRODUCT_CT_IMAGE ON dbo.RS_PRODUCT
GO

PRINT '<<< DROP INDEX FK_RS_PRODUCT_SK_MODEL >>>'
GO
DROP INDEX FK_RS_PRODUCT_SK_MODEL ON dbo.RS_PRODUCT
GO

PRINT '<<< DROP INDEX FK_RS_PRODUCT_SK_EQUIPMENT >>>'
GO
DROP INDEX FK_RS_PRODUCT_SK_EQUIPMENT ON dbo.RS_PRODUCT
GO


--
--DROP CONSTRAINT--
--
PRINT '<<< DROP CONSTRAINT FK_RS_COMING_CONTENT_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_COMING_CONTENT DROP CONSTRAINT FK_RS_COMING_CONTENT_RS_PRODUCT
GO

PRINT '<<< DROP CONSTRAINT FK_RS_ORDER_CONTENT_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_ORDER_CONTENT DROP CONSTRAINT FK_RS_ORDER_CONTENT_RS_PRODUCT
GO

PRINT '<<< DROP CONSTRAINT FK_RS_OUTGO_CONTENT_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_OUTGO_CONTENT DROP CONSTRAINT FK_RS_OUTGO_CONTENT_RS_PRODUCT
GO

PRINT '<<< DROP CONSTRAINT FK_RS_PRICE_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_PRICE DROP CONSTRAINT FK_RS_PRICE_RS_PRODUCT
GO

PRINT '<<< DROP CONSTRAINT FK_RS_RETURN_CONTENT_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_RETURN_CONTENT DROP CONSTRAINT FK_RS_RETURN_CONTENT_RS_PRODUCT
GO

PRINT '<<< DROP CONSTRAINT PK_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_PRODUCT DROP CONSTRAINT PK_RS_PRODUCT
GO

PRINT '<<< DROP CONSTRAINT FK_RS_PRODUCT_SK_MODEL >>>'
GO
ALTER TABLE dbo.RS_PRODUCT DROP CONSTRAINT FK_RS_PRODUCT_SK_MODEL
GO

PRINT '<<< DROP CONSTRAINT FK_RS_PRODUCT_SK_EQUIPMENT >>>'
GO
ALTER TABLE dbo.RS_PRODUCT DROP CONSTRAINT FK_RS_PRODUCT_SK_EQUIPMENT
GO

PRINT '<<< DROP CONSTRAINT FK_RS_PRODUCT_CT_IMAGE >>>'
GO
ALTER TABLE dbo.RS_PRODUCT DROP CONSTRAINT FK_RS_PRODUCT_CT_IMAGE
GO

PRINT '<<< DROP CONSTRAINT FK_RS_PRODUCT_CT_CATEGORY >>>'
GO
ALTER TABLE dbo.RS_PRODUCT DROP CONSTRAINT FK_RS_PRODUCT_CT_CATEGORY
GO

PRINT '<<< DROP CONSTRAINT FK_RS_PRODUCT_CT_BRAND >>>'
GO
ALTER TABLE dbo.RS_PRODUCT DROP CONSTRAINT FK_RS_PRODUCT_CT_BRAND
GO


--
--DROP TABLE--
--
PRINT '<<< DROP TABLE RS_PRODUCT >>>'
GO
DROP TABLE dbo.RS_PRODUCT
GO


--
--CREATE TABLE--
--
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

PRINT '<<< CREATE TABLE RS_PRODUCT >>>'
GO
CREATE TABLE dbo.RS_PRODUCT(
	ProductId bigint IDENTITY(1,1) NOT NULL,
	EquipmentId bigint NOT NULL,
	BrandId bigint NOT NULL,
	ModelId bigint NOT NULL,	
	ImageId bigint NULL,
	Name nvarchar(150) NOT NULL,
	Descr nvarchar(2000) NULL,
	Mass decimal(10, 3) NULL,
	Length decimal(10, 2) NULL,
	Width decimal(10, 2) NULL,
	Height decimal(10, 2) NULL,
	Color nvarchar(50) NULL,
	Power bigint NULL,
	Kit nvarchar(250) NULL,
	
 CONSTRAINT PK_RS_PRODUCT PRIMARY KEY CLUSTERED 
(ProductId ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


--
--ADD CONSTRAINT--
--
PRINT '<<< ADD CONSTRAINT FK_RS_PRODUCT_SK_EQUIPMENT >>>'
GO
ALTER TABLE dbo.RS_PRODUCT  WITH CHECK ADD CONSTRAINT FK_RS_PRODUCT_SK_EQUIPMENT FOREIGN KEY(EquipmentId)
REFERENCES dbo.SK_EQUIPMENT (EquipmentId)
GO

ALTER TABLE dbo.RS_PRODUCT CHECK CONSTRAINT FK_RS_PRODUCT_SK_EQUIPMENT
GO

PRINT '<<< ADD CONSTRAINT FK_RS_PRODUCT_CT_BRAND >>>'
GO
ALTER TABLE dbo.RS_PRODUCT  WITH CHECK ADD CONSTRAINT FK_RS_PRODUCT_CT_BRAND FOREIGN KEY(BrandId)
REFERENCES dbo.CT_BRAND (BrandId)
GO

ALTER TABLE dbo.RS_PRODUCT CHECK CONSTRAINT FK_RS_PRODUCT_CT_BRAND
GO

PRINT '<<< ADD CONSTRAINT FK_RS_PRODUCT_SK_MODEL >>>'
GO
ALTER TABLE dbo.RS_PRODUCT WITH CHECK ADD  CONSTRAINT FK_RS_PRODUCT_SK_MODEL FOREIGN KEY(ModelId)
REFERENCES dbo.SK_MODEL (ModelId)
GO

ALTER TABLE dbo.RS_PRODUCT CHECK CONSTRAINT FK_RS_PRODUCT_SK_MODEL
GO

PRINT '<<< ADD CONSTRAINT FK_RS_PRODUCT_CT_IMAGE >>>'
GO
ALTER TABLE dbo.RS_PRODUCT  WITH CHECK ADD CONSTRAINT FK_RS_PRODUCT_CT_IMAGE FOREIGN KEY(ImageId)
REFERENCES dbo.CT_IMAGE (ImageId)
GO

ALTER TABLE dbo.RS_PRODUCT CHECK CONSTRAINT FK_RS_PRODUCT_CT_IMAGE
GO

PRINT '<<< ADD CONSTRAINT FK_RS_RETURN_CONTENT_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_RETURN_CONTENT  WITH CHECK ADD CONSTRAINT FK_RS_RETURN_CONTENT_RS_PRODUCT FOREIGN KEY(ProductId)
REFERENCES dbo.RS_PRODUCT (ProductId)
GO

ALTER TABLE dbo.RS_RETURN_CONTENT CHECK CONSTRAINT FK_RS_RETURN_CONTENT_RS_PRODUCT
GO

PRINT '<<< ADD CONSTRAINT FK_RS_PRICE_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_PRICE  WITH CHECK ADD CONSTRAINT FK_RS_PRICE_RS_PRODUCT FOREIGN KEY(ProductId)
REFERENCES dbo.RS_PRODUCT (ProductId)
GO

ALTER TABLE dbo.RS_PRICE CHECK CONSTRAINT FK_RS_PRICE_RS_PRODUCT
GO

PRINT '<<< ADD CONSTRAINT FK_RS_OUTGO_CONTENT_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_OUTGO_CONTENT  WITH CHECK ADD CONSTRAINT FK_RS_OUTGO_CONTENT_RS_PRODUCT FOREIGN KEY(ProductId)
REFERENCES dbo.RS_PRODUCT (ProductId)
GO

ALTER TABLE dbo.RS_OUTGO_CONTENT CHECK CONSTRAINT FK_RS_OUTGO_CONTENT_RS_PRODUCT
GO

PRINT '<<< ADD CONSTRAINT FK_RS_ORDER_CONTENT_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_ORDER_CONTENT  WITH CHECK ADD CONSTRAINT FK_RS_ORDER_CONTENT_RS_PRODUCT FOREIGN KEY(ProductId)
REFERENCES dbo.RS_PRODUCT (ProductId)
GO

ALTER TABLE dbo.RS_ORDER_CONTENT CHECK CONSTRAINT FK_RS_ORDER_CONTENT_RS_PRODUCT
GO

PRINT '<<< ADD CONSTRAINT FK_RS_COMING_CONTENT_RS_PRODUCT >>>'
GO
ALTER TABLE dbo.RS_COMING_CONTENT  WITH CHECK ADD  CONSTRAINT FK_RS_COMING_CONTENT_RS_PRODUCT FOREIGN KEY(ProductId)
REFERENCES dbo.RS_PRODUCT (ProductId)
GO

ALTER TABLE dbo.RS_COMING_CONTENT CHECK CONSTRAINT FK_RS_COMING_CONTENT_RS_PRODUCT
GO



--
--CREATE INDEX--
--
PRINT '<<< ADD INDEX FK_RS_PRODUCT_SK_EQUIPMENT >>>'
GO
CREATE INDEX FK_RS_PRODUCT_SK_EQUIPMENT ON dbo.RS_PRODUCT(EquipmentId)
GO

PRINT '<<< ADD INDEX FK_RS_PRODUCT_CT_BRAND >>>'
GO
CREATE INDEX FK_RS_PRODUCT_CT_BRAND ON dbo.RS_PRODUCT(BrandId)
GO

PRINT '<<< ADD INDEX FK_RS_PRODUCT_SK_MODEL >>>'
GO
CREATE INDEX FK_RS_PRODUCT_SK_MODEL ON dbo.RS_PRODUCT(ModelId)
GO

PRINT '<<< ADD INDEX FK_RS_PRODUCT_CT_IMAGE >>>'
GO
CREATE INDEX FK_RS_PRODUCT_CT_IMAGE ON dbo.RS_PRODUCT(ImageId)
GO


PRINT '<<< ADD INDEX FK_RS_RETURN_CONTENT_RS_PRODUCT >>>'
GO
CREATE INDEX FK_RS_RETURN_CONTENT_RS_PRODUCT ON dbo.RS_RETURN_CONTENT(ProductId)
GO

PRINT '<<< ADD INDEX FK_RS_PRICE_RS_PRODUCT >>>'
GO
CREATE INDEX FK_RS_PRICE_RS_PRODUCT ON dbo.RS_PRICE(ProductId)
GO

PRINT '<<< ADD INDEX FK_RS_OUTGO_CONTENT_RS_PRODUCT >>>'
GO
CREATE INDEX FK_RS_OUTGO_CONTENT_RS_PRODUCT ON dbo.RS_OUTGO_CONTENT(ProductId)
GO

PRINT '<<< ADD INDEX FK_RS_ORDER_CONTENT_RS_PRODUCT >>>'
GO
CREATE NONCLUSTERED INDEX FK_RS_ORDER_CONTENT_RS_PRODUCT ON dbo.RS_ORDER_CONTENT(ProductId)
GO

PRINT '<<< ADD INDEX FK_RS_COMING_CONTENT_RS_PRODUCT >>>'
GO
CREATE NONCLUSTERED INDEX FK_RS_COMING_CONTENT_RS_PRODUCT ON dbo.RS_COMING_CONTENT(ProductId)
GO