USE ToolsStore
GO

IF DB_NAME() <> N'ToolsStore' SET NOEXEC ON
GO

--
-- Change transaction localization level (Изменить уровень локализации транзакции)
--
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

--
-- begin transaction
--
BEGIN TRANSACTION
GO

--
-- drop index
--
DROP INDEX FK_SK_EQUIPMENT_CT_CATEGORY ON dbo.SK_EQUIPMENT
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
--drop constraint
--
ALTER TABLE dbo.SK_EQUIPMENT DROP CONSTRAINT FK_SK_EQUIPMENT_CT_CATEGORY
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- alter column
--
ALTER TABLE dbo.SK_EQUIPMENT ALTER COLUMN CategoryId BIGINT NOT NULL;
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
--add constraint fk_sk_equipment_ct_category
--
ALTER TABLE dbo.SK_EQUIPMENT  WITH CHECK ADD CONSTRAINT FK_SK_EQUIPMENT_CT_CATEGORY FOREIGN KEY(CategoryId)
REFERENCES dbo.CT_CATEGORY (CategoryId)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

ALTER TABLE dbo.SK_EQUIPMENT CHECK CONSTRAINT FK_SK_EQUIPMENT_CT_CATEGORY
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- index fk_sk_equipment_ct_category 
--
CREATE NONCLUSTERED INDEX FK_SK_EQUIPMENT_CT_CATEGORY 
  ON dbo.SK_EQUIPMENT (CategoryId)
  ON [PRIMARY]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- commit transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
GO

--
-- set noexec to off (Установить NOEXEC в состояние off)
--
SET NOEXEC OFF
GO