USE ToolsStore;
GO

EXEC sp_rename 'dbo.MT_LOAD_RULE_SPEC.Name', 'FileName', 'COLUMN';
GO

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ADD PathToFile NVARCHAR(250);

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ADD Size INT NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ADD IsActive BIT NULL;
GO

SET DATEFORMAT ymd;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC 
	DROP COLUMN DateLoad;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ADD DateLoad DATETIME NULL;

UPDATE dbo.MT_LOAD_RULE_SPEC
SET PathToFile = lr.PathToXsd,
    IsActive = CAST(1 AS BIT),
    DateLoad = CAST('2019-01-01' AS DATETIME)
FROM dbo.MT_LOAD_RULE lr
WHERE dbo.MT_LOAD_RULE_SPEC.LoadRuleId = lr.LoadRuleId;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN Data VARBINARY(MAX) NOT NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN MimeType NVARCHAR(50) NOT NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN FileName NVARCHAR(100) NOT NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN PathToFile NVARCHAR(250) NOT NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN IsActive BIT NOT NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN DateLoad DATETIME NOT NULL;
GO