USE ToolsStore;
GO

SET DATEFORMAT ymd;

EXEC sp_rename 'dbo.MT_LOAD_RULE.FileName', 'Pattern', 'COLUMN'; 

EXEC sp_rename 'dbo.MT_LOAD_RULE.MethodLoad', 'Method', 'COLUMN'; 

ALTER TABLE dbo.MT_LOAD_RULE 
	DROP COLUMN PathToXsd;

ALTER TABLE dbo.MT_LOAD_RULE 
	DROP COLUMN XsdName;

ALTER TABLE dbo.MT_LOAD_RULE 
	DROP COLUMN IsActive;

ALTER TABLE dbo.MT_LOAD_RULE 
	DROP COLUMN Ord;

ALTER TABLE dbo.MT_LOAD_RULE
	ADD IsActive BIT;

ALTER TABLE dbo.MT_LOAD_RULE
	ADD Ord INT;

UPDATE dbo.MT_LOAD_RULE
SET IsActive = 1,
	Ord = CAST(lr.RowNumber AS INT)
FROM (SELECT LoadRuleId, ROW_NUMBER() OVER(ORDER BY LoadRuleId ASC) AS RowNumber
	  FROM dbo.MT_LOAD_RULE) lr
WHERE dbo.MT_LOAD_RULE.LoadRuleId = lr.LoadRuleId;

ALTER TABLE dbo.MT_LOAD_RULE
	ALTER COLUMN IsActive BIT NOT NULL;

ALTER TABLE dbo.MT_LOAD_RULE
	ALTER COLUMN Ord INT NOT NULL;
GO