USE ToolsStore;
GO

SET DATEFORMAT ymd;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC 
	DROP COLUMN DateLoad ;  

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ADD Size INT NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ADD DateLoad datetime NULL;

UPDATE dbo.MT_LOAD_RULE_SPEC
SET DateLoad = CAST('2019-01-01' AS DATETIME)

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN DateLoad DATETIME NOT NULL;

GO