USE ToolsStore;
GO

SET DATEFORMAT ymd;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC 
	DROP COLUMN DateLoad;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ADD PathToFile NVARCHAR(250);

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ADD Size INT NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ADD DateLoad DATETIME NULL;

UPDATE dbo.MT_LOAD_RULE_SPEC
SET PathToFile = lr.PathToXsd,
    DateLoad = CAST('2019-01-01' AS DATETIME)
FROM dbo.MT_LOAD_RULE lr
WHERE dbo.MT_LOAD_RULE_SPEC.LoadRuleId = lr.LoadRuleId;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN PathToFile NVARCHAR(250) NOT NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN DateLoad DATETIME NOT NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN MimeType NVARCHAR(50) NULL;

ALTER TABLE dbo.MT_LOAD_RULE_SPEC
	ALTER COLUMN FileName NVARCHAR(100) NULL;

GO