USE ToolsStore;
GO

DISABLE TRIGGER TR_FOR_INS_UPD_RS_PRICE ON RS_PRICE;  
GO  

UPDATE RS_PRICE
SET DateBegin = CONVERT(DATETIME, CONVERT(NVARCHAR(4), YEAR(DateBegin)+1) + '0101', 112)  --DATEADD(dd, DATEDIFF(dd, DateBegin, CONVERT(DATETIME, CONVERT(NVARCHAR(4), YEAR(DateBegin)+1) + '0101', 112)), DateBegin)
WHERE PriceId = 70;
GO

UPDATE RS_PRICE
SET DateEnd = DATEADD(dd, DATEDIFF(dd, DateEnd, CONVERT(DATETIME, CONVERT(NVARCHAR(4), YEAR(DateEnd)+1) + '0101', 112))-1, DateEnd)
WHERE PriceId = 1;
GO

ENABLE TRIGGER TR_FOR_INS_UPD_RS_PRICE ON RS_PRICE;  
GO  