USE ToolsStore
GO

--
-- Удаление ограничений таблицы dbo.RS_ORDER_CONTENT
--
ALTER TABLE dbo.RS_ORDER_CONTENT
  DROP CONSTRAINT FK_RS_ORDER_CONTENT_RS_ORDER
ALTER TABLE dbo.RS_ORDER_CONTENT
  DROP CONSTRAINT FK_RS_ORDER_CONTENT_RS_PRICE
ALTER TABLE dbo.RS_ORDER_CONTENT
  DROP CONSTRAINT FK_RS_ORDER_CONTENT_RS_PRODUCT
GO


--
-- Вставка данных в таблицу dbo.RS_ORDER_CONTENT
--
SET IDENTITY_INSERT dbo.RS_ORDER_CONTENT ON
GO

INSERT dbo.RS_ORDER_CONTENT(OrderContentId, OrderId, ProductId, PriceId, Quantity) VALUES (1, 1, 52, 52, 2)
INSERT dbo.RS_ORDER_CONTENT(OrderContentId, OrderId, ProductId, PriceId, Quantity) VALUES (2, 1, 68, 68, 1)
INSERT dbo.RS_ORDER_CONTENT(OrderContentId, OrderId, ProductId, PriceId, Quantity) VALUES (3, 2, 67, 67, 1)
INSERT dbo.RS_ORDER_CONTENT(OrderContentId, OrderId, ProductId, PriceId, Quantity) VALUES (4, 3, 58, 58, 1)
INSERT dbo.RS_ORDER_CONTENT(OrderContentId, OrderId, ProductId, PriceId, Quantity) VALUES (5, 4, 49, 49, 1)
INSERT dbo.RS_ORDER_CONTENT(OrderContentId, OrderId, ProductId, PriceId, Quantity) VALUES (6, 4, 53, 53, 1)
INSERT dbo.RS_ORDER_CONTENT(OrderContentId, OrderId, ProductId, PriceId, Quantity) VALUES (7, 5, 1, 70, 2)
INSERT dbo.RS_ORDER_CONTENT(OrderContentId, OrderId, ProductId, PriceId, Quantity) VALUES (8, 5, 2, 2, 1)
INSERT dbo.RS_ORDER_CONTENT(OrderContentId, OrderId, ProductId, PriceId, Quantity) VALUES (9, 6, 1, 70, 1)
INSERT dbo.RS_ORDER_CONTENT(OrderContentId, OrderId, ProductId, PriceId, Quantity) VALUES (10, 7, 1, 70, 1)
GO

SET IDENTITY_INSERT dbo.RS_ORDER_CONTENT OFF
GO

--
-- Задать Identity значение для dbo.RS_ORDER_CONTENT
--
DBCC CHECKIDENT('dbo.RS_ORDER_CONTENT', RESEED, 10) WITH NO_INFOMSGS
GO


--
-- Создание ограничений для таблицы dbo.RS_ORDER_CONTENT
--
ALTER TABLE dbo.RS_ORDER_CONTENT WITH NOCHECK
  ADD CONSTRAINT FK_RS_ORDER_CONTENT_RS_ORDER FOREIGN KEY (OrderId) REFERENCES dbo.RS_ORDER(OrderId) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE dbo.RS_ORDER_CONTENT WITH NOCHECK
  ADD CONSTRAINT FK_RS_ORDER_CONTENT_RS_PRICE FOREIGN KEY (PriceId) REFERENCES dbo.RS_PRICE(PriceId) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE dbo.RS_ORDER_CONTENT WITH NOCHECK
  ADD CONSTRAINT FK_RS_ORDER_CONTENT_RS_PRODUCT FOREIGN KEY (ProductId) REFERENCES dbo.RS_PRODUCT(ProductId) ON DELETE NO ACTION ON UPDATE NO ACTION
GO