USE master;  
GO 
 
IF DB_ID (N'ToolsStore2') IS NULL
  RETURN;
ALTER DATABASE ToolsStore2
SET SINGLE_USER --or RESTRICTED_USER
WITH ROLLBACK IMMEDIATE;
GO

IF DB_ID (N'ToolsStore2') IS NULL
  RETURN;
DROP DATABASE ToolsStore2;
GO